### ISSUE TITLE
Pegelonline HA Integration: Trend

### ISSUE THREAD

**Issue by klingbing** [mib1185/aiopegelonline#23]
Moin Michael,

DANKE für die Pegelonline Home Assistant Integration. Bis zu der Veröffentlichung hatte ich das über ein Homematic Skript gelöst, so ist es wesentlich komfortabler.

Mein Anwendungsszenario für die Pegelonline Daten: Ich wohne nahe der Elbe, in unserer Nachbarschaft sind noch Wasserleitungen (Überbleibsel eines Gemüseanbaugebiets vor 50 Jahren) welche von einer Pumpe an der Elbe mit Elbwasser für die Gartenbewässerung gespeist werden. Diese Pumpe Schaltet bei niedrigem Wasserstand ab, wodurch meine automatisierte Gartenbewässerung unmittelbar vom Wasserstand der Elbe abhängig ist.

Ich erlaube mir in diesem Zusammenhang einen Feature Request loszuwerden: Wäre es möglich, der Entität ein „Trend“ Attribut hinzuzufügen? Ich dachte dabei an die folgenden Zustände: Rising, Falling, Peak_High, Peak_Low oder ähnliches.

Ich habe mir dafür in HA einen eigenen Workaround gebaut, aber vielleicht ist das ja dennoch umsetzbar (und für andere nützlich).

Danke nochmal  für deine Arbeit an dieser Integration.

**Comment by mib1185** [comment]
Hi @klingbing,

es ist schön zu hören, dass die Integration Ihr Anwendung findet 🙂 

Aber leider habe ich keine guten Nachrichten, was deinen Feature Request angeht - die API von Pegelonline liefert keinerlei Daten über Vorhersagen, womit die Library hier [`aiopegelonline`](https://github.com/mib1185/aiopegelonline) auch keinerlei Vorhersagen treffen oder liefern kann (_die Daten sind stets Momentanaufnahmen_).

Somit lässt sich auch leider nichts Dergleichen in die [`pegel_online`](https://github.com/home-assistant/core/tree/dev/homeassistant/components/pegel_online) HA Integration einbauen.

Eventuell kannst du aber mit den [Min/Max](https://www.home-assistant.io/integrations/min_max/) oder [Riemann sum integral](https://www.home-assistant.io/integrations/integration/) (_frag mich bitte nicht, was genau ein Riemann integral ist 🙈_) Helper dir etwas passendes Zusammenbauen oder du fügst eine weitere Messstation der Elbe hinzu, welche Flussaufwärts liegt und versuchst aus den beiden Messpunkten dann eine Vorhersage zu treffen, ob der Pegel demnächst steigt oder nicht 🤔 

Grüße,
Micha
